### ISSUE TITLE
想请教一下，训练完模型之后想实时预测，输入数据怎么处理呀

### ISSUE THREAD

**Issue by mana58** [shenweichen/DeepCTR-Torch#101]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR-PyTorch/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.
想请教一下，训练完模型之后想实时预测，输入数据怎么处理呀，尤其是sparse feature，不知道模型训练的时候是否有保存feature映射表
**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - torch version [e.g. 1.2.0,]
 - deepctr-torch version [e.g. 0.1.0,]

**Comment by zanshuxun** [comment]
可以用一个字典存储每个feat对应的lbe对象（fit后的），然后用pickle.dump把这个字典保存下来
