### ISSUE TITLE
Example error run_classification_criteo.py

### ISSUE THREAD

**Issue by xinyu009** [shenweichen/DeepCTR-Torch#102]
**Describe the bug(问题描述)**
cuda ready...
cuda:0
Train on 160 samples, validate on 0 samples, 5 steps per epoch
Traceback (most recent call last):
  File "run_classification_criteo.py", line 62, in <module>
    batch_size=32, epochs=10, validation_split=0.0, verbose=2)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/deepctr_torch/models/basemodel.py", line 224, in fit
    total_loss.backward(retain_graph=True)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/xinyu/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128]], which is output 0 of SelectBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**To Reproduce(复现步骤)**
1. Just run run_classification_criteo.py

**Operating environment(运行环境):**
 - python version [3.7]
 - torch version [1.5.0]

**Additional context**

**Comment by huanhuancao** [comment]
Hello! Have you solved the problem?

**Comment by diff7** [comment]
same problem

**Comment by shenweichen** [comment]
we have solved this issue in new version , please use `pip install -U deepctr-torch` to upgrade.
