### ISSUE TITLE
AFM的bias没有初始化，导致实验结果不同。

### ISSUE THREAD

**Issue by Xstephen** [shenweichen/DeepCTR-Torch#105]
**Describe the bug(问题描述)**
AFM的bias没有初始化，导致实验结果不同。

**To Reproduce(复现步骤)**
由于这里bias没有初始化，且有梯度，导致不论是否使用attention network，每次结果均不同，且差异极大，一开始以为是随机种子问题，固定了之后，发现还是有问题。最后发现，原来有参数没有初始化。

**Operating environment(运行环境):**
 - python version [3.8]
 - torch version [1.4.0]
 - deepctr-torch version [0.8.0,]

**Additional context**
可以加上这一句
```python
for tensor in [self.attention_b]:
    nn.init.zeros_(tensor,)
```

**Comment by shenweichen** [comment]
非常感谢您细致的排查问题，我们会在近期的版本中对该问题进行修复，祝好！

**Comment by shenweichen** [comment]
新版本已修复，请使用`pip install -U deepctr-torch`更新
