### ISSUE TITLE
model save issue

### ISSUE THREAD

**Issue by aichenbaby** [shenweichen/DeepCTR-Torch#106]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR-PyTorch/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.
Traceback (most recent call last):
  File "test.py", line 113, in <module>
    torch.save(model,savePath+"DeepFM.h5")
  File "/home/zhangkai/.conda/envs/pytorchDeepCTR/lib/python3.7/site-packages/torch/serialization.py", line 224, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/zhangkai/.conda/envs/pytorchDeepCTR/lib/python3.7/site-packages/torch/serialization.py", line 149, in _with_file_like
    return body(f)
  File "/home/zhangkai/.conda/envs/pytorchDeepCTR/lib/python3.7/site-packages/torch/serialization.py", line 224, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/zhangkai/.conda/envs/pytorchDeepCTR/lib/python3.7/site-packages/torch/serialization.py", line 296, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'BaseModel._get_metrics.<locals>.<lambda>'
**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - torch version [e.g. 1.2.0,]
 - deepctr-torch version [e.g. 0.1.0,]

**Comment by mana58** [comment]
I have the same problem, do you know how to solve it?

**Comment by mana58** [comment]
I have the same problem, do you know how to solve it?

**Comment by mana58** [comment]
I have the same problem, do you know how to solve it?

**Comment by zanshuxun** [comment]
I can't reproduce this bug, have u tried a new version of deepctr-torch?  what's the version of your pickle?

**Comment by SCAUapc** [comment]
> I can't reproduce this bug, have u tried a new version of deepctr-torch? what's the version of your pickle?

> I have the same problem, do you know how to solve it?

I have the same problem, and i find that the problem is metrics
it will produce this question when i use 
metrics = ["binary_crossentropy", "auc", "logloss", "accuracy"]
but no matter when 
metrics = ["binary_crossentropy", "auc", "logloss"]

**Comment by gaohongkui** [comment]
此bug已解决，将在下一次release更新中解决。如急需使用，请参考修改
https://github.com/shenweichen/DeepCTR-Torch/blob/0dd01e697f3e95bcf4388e8519d8d3f5f16686e1/deepctr_torch/models/basemodel.py#L480-L500
