### ISSUE TITLE
如果训练数据太大，直接读取csv文件，压根内存放不下，不知道这些代码如何分批次读取文件的？

### ISSUE THREAD

**Issue by DaiJitao** [shenweichen/DeepCTR-Torch#108]
data = pd.read_csv('./criteo_sample.txt')
代码里这样读取文件的，请问如何分批处理，我的csv文件250G,哪有这么大的内存？

**Comment by shenweichen** [comment]
每次读一部分，按batch训练

**Comment by DaiJitao** [comment]
data = pd.read_csv('./criteo_sample.txt') 例子中写的代码是这样的，请问有batch训练的例子代码吗？没有找到？请问在什么地方查找呢？

**Comment by DaiJitao** [comment]
请问如何分批次处理的

**Comment by shenweichen** [comment]
每次读文件的一部分，然后执行训练过程，如此迭代
