### ISSUE TITLE
deepctr-torch版本怎么early_stopping呢？

### ISSUE THREAD

**Issue by wushupei1997** [shenweichen/DeepCTR-Torch#114]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR-PyTorch/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - torch version [e.g. 1.2.0,]
 - deepctr-torch version [e.g. 0.1.0,]

**Comment by WEIFZH** [comment]
如果没有提供接口的话，建议把这个项目拉到本地，对basemodel进行修改

**Comment by shenweichen** [comment]
> 如果没有提供接口的话，建议把这个项目拉到本地，对basemodel进行修改

我们的小伙伴已经在开发完成了，很快下个版本就会支持这个功能～

**Comment by WEIFZH** [comment]
> > 如果没有提供接口的话，建议把这个项目拉到本地，对basemodel进行修改
> 
> 我们的小伙伴已经开发完成了，很快下个版本就会支持这个功能～

amazing！给大佬打call，顺便问一下大佬库里面有哪些model是不支持多分类的呢？

**Comment by shenweichen** [comment]
> > > 如果没有提供接口的话，建议把这个项目拉到本地，对basemodel进行修改
> > 
> > 
> > 我们的小伙伴已经开发完成了，很快下个版本就会支持这个功能～
> 
> amazing！给大佬打call，顺便问一下大佬库里面有哪些model是不支持多分类的呢？

多分类目前是需要大家自行进行修改的，理论上所有的model都可以支持(最后一层使用softmax激活函数)，只是不同的实现方式效果不同，所以暂时没有提供统一的实现

**Comment by WEIFZH** [comment]
> > > > 如果没有提供接口的话，建议把这个项目拉到本地，对basemodel进行修改
> > > 
> > > 
> > > 我们的小伙伴已经开发完成了，很快下个版本就会支持这个功能～
> > 
> > 
> > amazing！给大佬打call，顺便问一下大佬库里面有哪些model是不支持多分类的呢？
> 
> 多分类目前是需要大家自行进行修改的，理论上所有的model都可以支持(最后一层使用softmax激活函数)，只是不同的实现方式效果不同，所以暂时没有提供统一的实现

明白啦，我也是这么修改的，感谢大佬！

**Comment by zanshuxun** [comment]
新版本已添加EarlyStopping功能，请使用`pip install -U deepctr-torch`更新。[使用样例](https://deepctr-torch.readthedocs.io/en/latest/FAQ.html#set-learning-rate-and-use-earlystopping)：

```python
from torch.optim import Adagrad
from deepctr_torch.models import DeepFM
from deepctr_torch.callbacks import EarlyStopping, ModelCheckpoint

model = DeepFM(linear_feature_columns,dnn_feature_columns)
model.compile(Adagrad(model.parameters(),0.1024),'binary_crossentropy',metrics=['binary_crossentropy'])

es = EarlyStopping(monitor='val_binary_crossentropy', min_delta=0, verbose=1, patience=0, mode='min')
mdckpt = ModelCheckpoint(filepath='model.ckpt', monitor='val_auc', verbose=1, save_best_only=True)
history = model.fit(model_input,data[target].values,batch_size=256,epochs=10,verbose=2,validation_split=0.2,callbacks=[es,mdckpt])
```
具体参数说明：https://tensorflow.google.cn/api_docs/python/tf/keras/callbacks/EarlyStopping
