### ISSUE TITLE
din模型问题

### ISSUE THREAD

**Issue by langzhining** [shenweichen/DeepCTR-Torch#128]
**Describe the bug(问题描述)**
1 din.py文件forward 中keys length为常数1，不表示序列长度
2 部分sparse fear特征取了两次，lookup embedding中mask feature list不起作用

**To Reproduce(复现步骤)**

**Operating environment(运行环境):**
 - python version [e.g. 3.5, 3.6]
 - torch version [e.g. 1.1.0, 1.2.0]
 - deepctr-torch version [e.g. 0.1.0,]

**Additional context**

**Comment by zanshuxun** [comment]
非常感谢您细致地排查问题，我们会在近期的版本中对该问题进行修复，祝好！

**Comment by zanshuxun** [comment]
Q1:
已修复，详见https://github.com/shenweichen/DeepCTR-Torch/commit/61b5775bf695b695d205ac9154528480425fcebe
参考了`dien.py`中获取历史序列长度的方式，输入数据需要增加`behavior_length`
暂未合并至master分支，可以先参考[dev-zsx](https://github.com/shenweichen/DeepCTR-Torch/tree/dev-zsx)分支

Q2:
（1）【部分sparse fear特征取了两次】 您是指这两次吗：
https://github.com/shenweichen/DeepCTR-Torch/blob/bc881dcd417fec64f840b0cacce124bc86b3687c/deepctr_torch/models/din.py#L82-L83

https://github.com/shenweichen/DeepCTR-Torch/blob/bc881dcd417fec64f840b0cacce124bc86b3687c/deepctr_torch/models/din.py#L90
第一次取出来的sparse_embedding_list在后面确实没有用到，[已优化](https://github.com/shenweichen/DeepCTR-Torch/commit/61b5775bf695b695d205ac9154528480425fcebe#diff-f85d5b1785865c14c6f05e3c32a01c9c194d1e9cf0c02449ba007d2eb7fe3445R82)。

（2）【lookup embedding中mask feature list不起作用】
embedding_lookup函数中的mask_feat_list参数是用于hash的，详见[DeepCTR](https://github.com/shenweichen/DeepCTR/blob/master/deepctr/inputs.py#L54)。目前torch版还未加入hash，所以还没有用到。

**Comment by zanshuxun** [comment]
Hi, we have solved this issue in [v0.2.4](https://github.com/shenweichen/DeepCTR-Torch/releases/tag/v0.2.4), please use `pip install -U deepctr-torch` to upgrade.
