### ISSUE TITLE
DCN-M的tf版本近期会更新吗

### ISSUE THREAD

**Issue by currywu123** [shenweichen/DeepCTR-Torch#129]

**Comment by zanshuxun** [comment]
目前dev-zsx分支已经增加DCN-M、DCN-Mix模型并测试通过了，可以先参考一下：
https://github.com/shenweichen/DeepCTR/blob/dev-zsx/deepctr/models/dcn.py
https://github.com/shenweichen/DeepCTR/blob/dev-zsx/deepctr/models/dcnmix.py
后续发布新版本时会合并至master分支

**Comment by zanshuxun** [comment]
[DeepCTR v0.8.3 ](https://github.com/shenweichen/DeepCTR/releases/tag/v0.8.3) 中已添加DCN-M（DCN V2）
