### ISSUE TITLE
如果我想实现多分类，应该在哪里进行改动呢

### ISSUE THREAD

**Issue by wushupei1997** [shenweichen/DeepCTR-Torch#133]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR-PyTorch/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - torch version [e.g. 1.2.0,]
 - deepctr-torch version [e.g. 0.1.0,]

**Comment by zanshuxun** [comment]
请参考https://github.com/shenweichen/DeepCTR-Torch/issues/117
