### ISSUE TITLE
更新0.2.3后import deepctr_torch出现"ImportError: DLL load failed: 找不到指定的模块。"错误

### ISSUE THREAD

**Issue by wushupei1997** [shenweichen/DeepCTR-Torch#134]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR-PyTorch/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version 3.5
 - torch version 1.2.0
 - deepctr-torch version 0.2.3

**Comment by zanshuxun** [comment]
贴一下完整的报错信息吧
是不是tensorflow没装好？0.2.3需要用到tensorflow的callbacks

**Comment by wushupei1997** [comment]
![image](https://user-images.githubusercontent.com/57393009/99229870-8a0fe600-2829-11eb-973b-17851f3e017c.png)

**Comment by wushupei1997** [comment]
tensorflow需要安装什么版本呢

**Comment by zanshuxun** [comment]
和deepctr的版本要求一致 1.x和2.x都可以
看这个报错是不是tensorflow没装好呀 试下import tensorflow能成功吗

**Comment by wushupei1997** [comment]
好像不行

**Comment by wushupei1997** [comment]
> 和deepctr的版本要求一致 1.x和2.x都可以
> 看这个报错是不是tensorflow没装好呀 试下import tensorflow能成功吗

好像不行。。。

**Comment by wushupei1997** [comment]
> 卸载用conda重装试试？
> 不行的话装其他版本的tf试试？比如1.12.0

好的，非常感谢
