### ISSUE TITLE
报错RuntimeError: cublas runtime error : library not initialized at ..\aten\src\THC\THCGeneral.cpp:216

### ISSUE THREAD

**Issue by wushupei1997** [shenweichen/DeepCTR-Torch#135]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR-PyTorch/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version 3.5
 - torch version 1.2.0
 - deepctr-torch version 0.2.2

**Comment by zanshuxun** [comment]
可以贴一下完整的日志吗

**Comment by wushupei1997** [comment]
> 可以贴一下完整的日志吗

![image](https://user-images.githubusercontent.com/57393009/99897849-f2524200-2cd7-11eb-9b12-0a6fc43f0cb0.png)

**Comment by zanshuxun** [comment]
是不是显存已经被占满了？

**Comment by wushupei1997** [comment]
> 是不是显存已经被占满了？
应该不会，我没有开其他程序了，标签数据都没有空值啥的

**Comment by zanshuxun** [comment]
建议您那边尝试一下：
1 看一下目前显存占用情况
2 用cpu跑试试

**Comment by zanshuxun** [comment]
例子程序能跑通吗

**Comment by wushupei1997** [comment]
> 例子程序能跑通吗

例子可以，就是使用自己的数据出现的问题，用cpu跑：
![image](https://user-images.githubusercontent.com/57393009/99898089-cd5ece80-2cd9-11eb-9dc8-c72f2d5174f6.png)

**Comment by zanshuxun** [comment]
取embedding时发生下标越界错误了 是不是实际数据里有超过embedding_size的数啊

**Comment by wushupei1997** [comment]
> 取embedding时发生下标越界错误了 是不是实际数据里有超过embedding_size的数啊

有些数值是蛮大的，但是使用了minmax缩放到了（0，1），这样还是会导致越界吗

**Comment by wushupei1997** [comment]
> 取embedding时发生下标越界错误了 是不是实际数据里有超过embedding_size的数啊

这样子，那我看看数据，embedding_size可以自定义吗

**Comment by zanshuxun** [comment]
> > 取embedding时发生下标越界错误了 是不是实际数据里有超过embedding_size的数啊
> 
> 这样子，那我看看数据，embedding_size可以自定义吗
### vocabulary_size
这里的`data[feat].nunique()`就是`vocabulary_size`，需要用户根据实际数据来确定
https://github.com/shenweichen/DeepCTR-Torch/blob/bc881dcd417fec64f840b0cacce124bc86b3687c/examples/run_classification_criteo.py#L30
### embedding_size
embedding_size默认是4 可以在调用SparseFeat()时传参修改
https://github.com/shenweichen/DeepCTR-Torch/blob/bc881dcd417fec64f840b0cacce124bc86b3687c/deepctr_torch/inputs.py#L20-L26
看这个报错应该是vocabulary_size的问题

**Comment by wushupei1997** [comment]
> > > 取embedding时发生下标越界错误了 是不是实际数据里有超过embedding_size的数啊
> > 
> > 
> > 这样子，那我看看数据，embedding_size可以自定义吗
> 
> ### vocabulary_size
> 这里的`data[feat].nunique()`就是`vocabulary_size`，需要用户根据实际数据来确定
> https://github.com/shenweichen/DeepCTR-Torch/blob/bc881dcd417fec64f840b0cacce124bc86b3687c/examples/run_classification_criteo.py#L30
> 
> ### embedding_size
> embedding_size默认是4 可以在调用SparseFeat()时传参修改
> https://github.com/shenweichen/DeepCTR-Torch/blob/bc881dcd417fec64f840b0cacce124bc86b3687c/deepctr_torch/inputs.py#L20-L26
> 
> 
> 看这个报错应该是vocabulary_size的问题

嗷嗷，超级感谢！！！！！

**Comment by wushupei1997** [comment]
还想问一下，我想把训练好的embedding层取出来，改如何做呢

**Comment by zanshuxun** [comment]
> 还想问一下，我想把训练好的embedding层取出来，改如何做呢

找到对应的embedding层 通过`.weight`方法获取embedding矩阵
以`run_classification_criteo.py`为例，其model结构为：
```
DeepFM(
  (embedding_dict): ModuleDict(
    (C1): Embedding(27, 4)
    (C10): Embedding(142, 4)
    (C11): Embedding(173, 4)
    (C12): Embedding(170, 4)
    (C13): Embedding(166, 4)
    (C14): Embedding(14, 4)
    (C15): Embedding(170, 4)
    (C16): Embedding(168, 4)
    (C17): Embedding(9, 4)
    (C18): Embedding(127, 4)
    (C19): Embedding(44, 4)
    (C2): Embedding(92, 4)
    (C20): Embedding(4, 4)
    (C21): Embedding(169, 4)
    (C22): Embedding(6, 4)
    (C23): Embedding(10, 4)
    (C24): Embedding(125, 4)
    (C25): Embedding(20, 4)
    (C26): Embedding(90, 4)
    (C3): Embedding(172, 4)
    (C4): Embedding(157, 4)
    (C5): Embedding(12, 4)
    (C6): Embedding(7, 4)
    (C7): Embedding(183, 4)
    (C8): Embedding(19, 4)
    (C9): Embedding(2, 4)
  )
  (linear_model): Linear(
    (embedding_dict): ModuleDict(
      (C1): Embedding(27, 1)
      (C10): Embedding(142, 1)
      (C11): Embedding(173, 1)
      (C12): Embedding(170, 1)
      (C13): Embedding(166, 1)
      (C14): Embedding(14, 1)
      (C15): Embedding(170, 1)
      (C16): Embedding(168, 1)
      (C17): Embedding(9, 1)
      (C18): Embedding(127, 1)
      (C19): Embedding(44, 1)
      (C2): Embedding(92, 1)
      (C20): Embedding(4, 1)
      (C21): Embedding(169, 1)
      (C22): Embedding(6, 1)
      (C23): Embedding(10, 1)
      (C24): Embedding(125, 1)
      (C25): Embedding(20, 1)
      (C26): Embedding(90, 1)
      (C3): Embedding(172, 1)
      (C4): Embedding(157, 1)
      (C5): Embedding(12, 1)
      (C6): Embedding(7, 1)
      (C7): Embedding(183, 1)
      (C8): Embedding(19, 1)
      (C9): Embedding(2, 1)
    )
  )
  (out): PredictionLayer()
  (fm): FM()
  (dnn): DNN(
    (dropout): Dropout(p=0, inplace=False)
    (linears): ModuleList(
      (0): Linear(in_features=117, out_features=256, bias=True)
      (1): Linear(in_features=256, out_features=128, bias=True)
    )
    (activation_layers): ModuleList(
      (0): ReLU(inplace=True)
      (1): ReLU(inplace=True)
    )
  )
  (dnn_linear): Linear(in_features=128, out_features=1, bias=False)
)
```
如果想取出`C1`特征的embedding矩阵：
`model.embedding_dict['C1'].weight`
```
Parameter containing:
tensor([[-3.7980e-05, -1.6603e-04,  9.8783e-05,  1.1607e-04],
        [-9.5226e-05,  5.7875e-05, -6.9740e-05,  5.1303e-05],
        [ 3.1489e-05, -3.8243e-05,  1.2341e-04,  4.3117e-05],
        [-1.4858e-04, -5.6954e-06, -8.2194e-05, -7.8161e-06],
        [ 1.4290e-04, -4.5746e-05,  8.1582e-05, -1.3813e-04],
        [ 7.6686e-05,  8.5914e-05,  1.6777e-04,  5.9753e-05],
        [ 9.7042e-05,  2.7979e-05,  5.9640e-05, -1.2196e-04],
        [-1.6065e-04, -1.3333e-04,  3.5254e-05, -4.3688e-06],
        [ 1.0936e-04,  1.0580e-04,  4.5443e-05, -1.6783e-04],
        [ 3.2704e-06,  1.1384e-04,  3.1574e-05,  9.6371e-06],
        [ 1.8548e-04,  7.2060e-05, -1.2791e-05, -1.3375e-04],
        [-3.8205e-05, -3.6484e-05,  4.0148e-05, -6.5716e-05],
        [ 1.6983e-04,  8.7041e-05,  5.8834e-06,  5.6575e-05],
        [-3.0855e-05,  2.2118e-05, -5.3703e-05, -7.1927e-05],
        [ 4.4076e-05, -1.5751e-04,  2.1143e-05, -1.4081e-04],
        [ 2.3678e-06,  1.4679e-05, -1.1664e-04,  1.8402e-04],
        [ 4.4137e-05, -5.3945e-05,  6.5661e-05, -5.8425e-05],
        [ 5.7366e-05,  2.8113e-04,  8.2743e-05, -1.0466e-05],
        [ 1.2911e-04,  1.7044e-05,  1.7556e-05, -2.6281e-05],
        [-8.2843e-05,  5.2515e-05,  4.2607e-05,  2.3768e-05],
        [ 6.6649e-05, -3.5260e-05, -7.9192e-05, -1.5185e-05],
        [ 1.1581e-04, -9.3952e-05,  1.1896e-04,  2.6584e-06],
        [ 1.1022e-04,  1.5320e-04,  7.4962e-05,  7.4654e-05],
        [ 1.1383e-04,  1.1493e-04,  1.2575e-05, -2.4837e-05],
        [-1.1016e-04, -1.6549e-04,  1.5992e-04, -1.0300e-04],
        [-1.3990e-04, -1.4093e-05, -7.9595e-05, -5.0276e-06],
        [-4.0105e-05, -5.9200e-05,  1.9921e-05,  1.3136e-04]],
       requires_grad=True)
```
如果需要转为numpy：
`model.embedding_dict['C1'].weight.data.numpy()`

**Comment by wushupei1997** [comment]
> > 还想问一下，我想把训练好的embedding层取出来，改如何做呢
> 
> 找到对应的embedding层 通过`.weight`方法获取embedding矩阵
> 以`run_classification_criteo.py`为例，其model结构为：
> 
> ```
> DeepFM(
>   (embedding_dict): ModuleDict(
>     (C1): Embedding(27, 4)
>     (C10): Embedding(142, 4)
>     (C11): Embedding(173, 4)
>     (C12): Embedding(170, 4)
>     (C13): Embedding(166, 4)
>     (C14): Embedding(14, 4)
>     (C15): Embedding(170, 4)
>     (C16): Embedding(168, 4)
>     (C17): Embedding(9, 4)
>     (C18): Embedding(127, 4)
>     (C19): Embedding(44, 4)
>     (C2): Embedding(92, 4)
>     (C20): Embedding(4, 4)
>     (C21): Embedding(169, 4)
>     (C22): Embedding(6, 4)
>     (C23): Embedding(10, 4)
>     (C24): Embedding(125, 4)
>     (C25): Embedding(20, 4)
>     (C26): Embedding(90, 4)
>     (C3): Embedding(172, 4)
>     (C4): Embedding(157, 4)
>     (C5): Embedding(12, 4)
>     (C6): Embedding(7, 4)
>     (C7): Embedding(183, 4)
>     (C8): Embedding(19, 4)
>     (C9): Embedding(2, 4)
>   )
>   (linear_model): Linear(
>     (embedding_dict): ModuleDict(
>       (C1): Embedding(27, 1)
>       (C10): Embedding(142, 1)
>       (C11): Embedding(173, 1)
>       (C12): Embedding(170, 1)
>       (C13): Embedding(166, 1)
>       (C14): Embedding(14, 1)
>       (C15): Embedding(170, 1)
>       (C16): Embedding(168, 1)
>       (C17): Embedding(9, 1)
>       (C18): Embedding(127, 1)
>       (C19): Embedding(44, 1)
>       (C2): Embedding(92, 1)
>       (C20): Embedding(4, 1)
>       (C21): Embedding(169, 1)
>       (C22): Embedding(6, 1)
>       (C23): Embedding(10, 1)
>       (C24): Embedding(125, 1)
>       (C25): Embedding(20, 1)
>       (C26): Embedding(90, 1)
>       (C3): Embedding(172, 1)
>       (C4): Embedding(157, 1)
>       (C5): Embedding(12, 1)
>       (C6): Embedding(7, 1)
>       (C7): Embedding(183, 1)
>       (C8): Embedding(19, 1)
>       (C9): Embedding(2, 1)
>     )
>   )
>   (out): PredictionLayer()
>   (fm): FM()
>   (dnn): DNN(
>     (dropout): Dropout(p=0, inplace=False)
>     (linears): ModuleList(
>       (0): Linear(in_features=117, out_features=256, bias=True)
>       (1): Linear(in_features=256, out_features=128, bias=True)
>     )
>     (activation_layers): ModuleList(
>       (0): ReLU(inplace=True)
>       (1): ReLU(inplace=True)
>     )
>   )
>   (dnn_linear): Linear(in_features=128, out_features=1, bias=False)
> )
> ```
> 
> 如果想取出`C1`特征的embedding矩阵：
> `model.embedding_dict['C1'].weight`
> 
> ```
> Parameter containing:
> tensor([[-3.7980e-05, -1.6603e-04,  9.8783e-05,  1.1607e-04],
>         [-9.5226e-05,  5.7875e-05, -6.9740e-05,  5.1303e-05],
>         [ 3.1489e-05, -3.8243e-05,  1.2341e-04,  4.3117e-05],
>         [-1.4858e-04, -5.6954e-06, -8.2194e-05, -7.8161e-06],
>         [ 1.4290e-04, -4.5746e-05,  8.1582e-05, -1.3813e-04],
>         [ 7.6686e-05,  8.5914e-05,  1.6777e-04,  5.9753e-05],
>         [ 9.7042e-05,  2.7979e-05,  5.9640e-05, -1.2196e-04],
>         [-1.6065e-04, -1.3333e-04,  3.5254e-05, -4.3688e-06],
>         [ 1.0936e-04,  1.0580e-04,  4.5443e-05, -1.6783e-04],
>         [ 3.2704e-06,  1.1384e-04,  3.1574e-05,  9.6371e-06],
>         [ 1.8548e-04,  7.2060e-05, -1.2791e-05, -1.3375e-04],
>         [-3.8205e-05, -3.6484e-05,  4.0148e-05, -6.5716e-05],
>         [ 1.6983e-04,  8.7041e-05,  5.8834e-06,  5.6575e-05],
>         [-3.0855e-05,  2.2118e-05, -5.3703e-05, -7.1927e-05],
>         [ 4.4076e-05, -1.5751e-04,  2.1143e-05, -1.4081e-04],
>         [ 2.3678e-06,  1.4679e-05, -1.1664e-04,  1.8402e-04],
>         [ 4.4137e-05, -5.3945e-05,  6.5661e-05, -5.8425e-05],
>         [ 5.7366e-05,  2.8113e-04,  8.2743e-05, -1.0466e-05],
>         [ 1.2911e-04,  1.7044e-05,  1.7556e-05, -2.6281e-05],
>         [-8.2843e-05,  5.2515e-05,  4.2607e-05,  2.3768e-05],
>         [ 6.6649e-05, -3.5260e-05, -7.9192e-05, -1.5185e-05],
>         [ 1.1581e-04, -9.3952e-05,  1.1896e-04,  2.6584e-06],
>         [ 1.1022e-04,  1.5320e-04,  7.4962e-05,  7.4654e-05],
>         [ 1.1383e-04,  1.1493e-04,  1.2575e-05, -2.4837e-05],
>         [-1.1016e-04, -1.6549e-04,  1.5992e-04, -1.0300e-04],
>         [-1.3990e-04, -1.4093e-05, -7.9595e-05, -5.0276e-06],
>         [-4.0105e-05, -5.9200e-05,  1.9921e-05,  1.3136e-04]],
>        requires_grad=True)
> ```
> 
> 如果需要转为numpy：
> `model.embedding_dict['C1'].weight.data.numpy()`

不同的embedding层有什么不同吗，因为我想的是把其取出来作为特征数据的编码

**Comment by zanshuxun** [comment]
对应不同的特征啊

**Comment by wushupei1997** [comment]
> 对应不同的特征啊

懂了，：）

**Comment by zanshuxun** [comment]
This is not an actual DeepCTR-Torch bug, so closing here.
