### ISSUE TITLE
如何在cpu环境加载GPU训练的模型参数

### ISSUE THREAD

**Issue by LuckyDoggy** [shenweichen/DeepCTR-Torch#145]
我在GPU环境训练DeepFM模型之后，保存了参数字典，在CPU环境加载时会报错
RuntimeError: Error(s) in loading state_dict for DeepFM:
	Missing key(s) in state_dict: "linear_model.weight". 
查看CPU和GPU初始化的DeepFM模型发现，CPU初始化的模型的参数字典会多一个'linear_model.weight'字段。

**Operating environment(运行环境):**
 - python version [3.6]
 - torch version [1.1.0]
 - deepctr-torch version [ 0.2.3]

**Comment by zanshuxun** [comment]
v0.2.4已解决此bug，请使用`pip install -U deepctr-torch`更新
关于此bug详见#87

**Comment by LuckyDoggy** [comment]
> v0.2.4已解决此bug，请使用`pip install -U deepctr-torch`更新
> 关于此bug详见#87

好的，感谢回复
