### ISSUE TITLE
din相关疑惑

### ISSUE THREAD

**Issue by Ohikuy** [shenweichen/DeepCTR-Torch#149]
**Describe the question(问题描述)**
(I am new in DIN,here are some questions on DIN example,as follows)
  我是一个对于DIN的新手，我对于example中的din框架有一些疑问，具体如下：
  
(the comment about history_feature_list is _to indicate  sequence sparse field_)
1. 注释中的param history_feature_list: list,to indicate  sequence sparse field

(but what about the history_feature_list actually mean, can you take some more specific example)
  **param history_feature_list是什么，能否举个更具体的例子**
(I can't understand just by  behavior_feature_list = ["item_id", "cate_id"])
  behavior_feature_list = ["item_id", "cate_id"]这一个没能理解

(and how to choose suitable size about vocabulary_size and embedding_dim)
2.如何确定SparseFeat的vocabulary_size和embedding_dim

(thanks a lot if you can provide any help!)
如果能有一些帮助，万分感谢！

**Comment by Ohikuy** [comment]
i got it

**Comment by JJia000** [comment]
> **描述问题（问题描述）**
> （我是
> DIN 新手，这里有一些 DIN 例子的问题，如下）
> 
> （history_feature_list 的注释是_表示序列稀疏字段_）
> 
> 1. 注释中的param history_feature_list: list，表示序列稀疏字段
> 
> （但是history_feature_list实际上是什么意思，你 能不能
> **举**一些更具体的例子）**param history_feature_list是什么，可以举个更具体的例子**
> （我不能通过behavior_feature_list = [“item_id”，“cate_id”]来理解）
> behavior_feature_list = ["item_id", "cate_id"]这一个没能理解的
> 
> （以及如何选择合适大小的vocabulary_size和embedding_dim）
> 2.如何确定SparseFeat的vocabulary_size和embedding_dim
> 
> （如果你能提供任何帮助
> ，非常感谢！）如果能有一些帮助，万分感谢！



> 我知道了

您好，您能成功运行din模型了吗？我和你有相同的问题，若您知道了，可否也告知我一下，谢谢~
