### ISSUE TITLE
torch.load can not use cpu

### ISSUE THREAD

**Issue by SCAUapc** [shenweichen/DeepCTR-Torch#150]
I use gpu to train model, and save it by torch.save(model, model_path)

But when i use it to predict online, I use "model = torch.load(model_path, map_location=torch.device("cpu"))"

but model.device is still show thath "cuda:1"

How can i use the model by cpu online?

**Comment by zanshuxun** [comment]
There are two ways to  save and load the model  in pytorch. You should use the 2nd in your scenario. Details can be seen in pytorch doc.

## 1. Save and load the entire model.
torch.save(resnet, 'model.ckpt')
model = torch.load('model.ckpt')

## 2. Save and load only the model parameters (recommended).
torch.save(resnet.state_dict(), 'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))

**Comment by SCAUapc** [comment]
> There are two ways to save and load the model in pytorch. You should use the 2nd in your scenario. Details can be seen in pytorch doc.
> 
> ## 1. Save and load the entire model.
> torch.save(resnet, 'model.ckpt')
> model = torch.load('model.ckpt')
> 
> ## 2. Save and load only the model parameters (recommended).
> torch.save(resnet.state_dict(), 'params.ckpt')
> resnet.load_state_dict(torch.load('params.ckpt'))

Thanks ! Now it is available
