### ISSUE TITLE
请问库中的推荐算法模型可以做分布式训练吗？

### ISSUE THREAD

**Issue by wushupei1997** [shenweichen/DeepCTR-Torch#154]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR-PyTorch/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - torch version [e.g. 1.7.0,]
 - deepctr-torch version [e.g. 0.2.4,]

**Comment by zanshuxun** [comment]
目前[v0.2.6](https://github.com/shenweichen/DeepCTR-Torch/releases/tag/v0.2.6)支持了单机多卡分布式

**Comment by phoenixzw** [comment]
现在这个nn.DataParallel 弊端很大，会用不少额外资源，现在pytorch已经推荐完全用 nn.parallel.DistributedDataParallel 作为代替: https://pytorch.org/docs/stable/notes/cuda.html#cuda-nn-ddp-instead
咱们有计划用DistributedDataParallel replace DataParallel吗？
谢谢！
