### ISSUE TITLE
Early-stopping Bug

### ISSUE THREAD

**Issue by WeiyuCheng** [shenweichen/DeepCTR-Torch#171]
**Describe the bug(问题描述)**
尝试文档中提供的early-stopping代码报错或结果不对（尝试了tensorflow 1.13, 1.14和1.15）

**To Reproduce(复现步骤)**
安装tensorflow 1.13，1.14或1.15版本；运行
```
from torch.optim import Adagrad
from deepctr_torch.models import DeepFM
from deepctr_torch.callbacks import EarlyStopping, ModelCheckpoint

model = DeepFM(linear_feature_columns,dnn_feature_columns)
model.compile(Adagrad(model.parameters(),0.1024),'binary_crossentropy',metrics=['binary_crossentropy'])

es = EarlyStopping(monitor='val_binary_crossentropy', min_delta=0, verbose=1, patience=0, mode='min')
mdckpt = ModelCheckpoint(filepath = 'model.ckpt', save_best_only= True)
history = model.fit(model_input,data[target].values,batch_size=256,epochs=10,verbose=2,validation_split=0.2,callbacks=[es,mdckpt])
print(history)
```

**Operating environment(运行环境):**
 - python version [3.7]
 - torch version [1.3.0]
 - deepctr-torch version [0.2.6]

**Additional context**
1.13下每一轮都报Can save best model only with val_loss available, skipping. 最终没有模型文件保存
1.14和1.15下都分别有报错：
1.14：
```
callbacks.on_train_end() File "/opt/conda/lib/python3.7/site-packages/keras/callbacks.py", line 142, in on_train_end callback.on_train_end(logs) File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 940, in on_train_end
if self.model._ckpt_saved_epoch is not None: 
AttributeError: 'None' object has no attribute '_ckpt_saved_epoch'
```
1.15：
```
callback.on_train_end(logs) File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 905, in on_train_begin
if self.model._in_multi_worker_mode():
AttributeError: 'None' object has no attribute '_in_multi_worker_mode'
```

**Comment by zanshuxun** [comment]
抱歉

1、文档中的例子确实有问题，ModelCheckpoint需要指定更多参数，例如：
`mdckpt = ModelCheckpoint(filepath='model.ckpt', monitor='val_binary_crossentropy', verbose=1, save_best_only=True, mode='min')`
这样改了之后，在tf1.12/1.13下是ok的

2、tf1.14和tf1.15下确实存在bug，之前我这边测试的tf版本不够多，目前已在dev-zsx分支下的commit [05adbd1](https://github.com/shenweichen/DeepCTR-Torch/commit/05adbd1060a97e96c2fda4fe9aaa0aca12c33242)中修复了这些bug（在tf1.4、1.12、1.13、1.14、1.15、2.1下测试可用）。

我们会在近期的新版本中对此问题进行修复，祝好！
