### ISSUE TITLE
Linear Layer in AutoInt

### ISSUE THREAD

**Issue by rohit497** [shenweichen/DeepCTR-Torch#175]
The AutoInt model implementation has a linear layer from which the logit is obtained before the features are passed into the attention and deep layers. However, the paper has no mention of such a linear layer. Why is this in the model?

**Comment by abedshantti** [comment]
@zanshuxun @shenweichen Can we get a clarification regarding the purpose of the linear layer in the AutoInt model?

**Comment by zanshuxun** [comment]
The aim of the linear part is to keep extendibility, you can set `linear_feature_columns=[]` to make linear part unused.
