### ISSUE TITLE
[DIN] models/din.py 的第 94~97行是否有点问题

### ISSUE THREAD

**Issue by cuihu1998** [shenweichen/DeepCTR-Torch#176]
是代码写错了吗？ 运行的是examples/run_din.py。

**Comment by cuihu1998** [comment]
从din.py的第102行开始
`
        sequence_embed_dict = varlen_embedding_lookup(X, self.embedding_dict, self.feature_index,
                                                      self.sparse_varlen_feature_columns)
        sequence_embed_list = get_varlen_pooling_list(sequence_embed_dict, X, self.feature_index,
                                                      self.sparse_varlen_feature_columns, self.device)
`

  sequence_embed_dict实际得到的是经过Embedding后输出的Tensor组成的dict，然后作get_varlen_polling_list的第一个参数传入；但是get_varlen_polling_list的第一个参数应该是一个放着Embedding Layer的dict...
  运行examples/run_din.py不会报错，是因为这里的sequence_embed_dict 和 self.sparse_varlen_feature_columns直接就是一个空数组 ：[]。
  整体逻辑应该是有问题，在此提问。

**Comment by zanshuxun** [comment]
感谢您细致地排查问题，我们会在近期的版本中对该问题进行修复，祝好！

代码逻辑是有问题的，get_varlen_pooling_list()两次调用的入参类型不一致。

第一次调用：
https://github.com/shenweichen/DeepCTR-Torch/blob/8265c75237e473c7f238fd6ba44cb09f55d1d9a9/deepctr_torch/models/din.py#L84
https://github.com/shenweichen/DeepCTR-Torch/blob/8265c75237e473c7f238fd6ba44cb09f55d1d9a9/deepctr_torch/models/basemodel.py#L362
self.input_from_feature_columns()里调用了get_varlen_pooling_list()。这时第一个输入embedding_dict的value为**embed layer**。

第二次调用：
https://github.com/shenweichen/DeepCTR-Torch/blob/8265c75237e473c7f238fd6ba44cb09f55d1d9a9/deepctr_torch/models/din.py#L94-L99
处理非hist feat类变长特征时，也会调用get_varlen_pooling_list()。这时第一个输入参数embedding_dict的value为**tensor**。而get_varlen_pooling_list()中做pooling之前会根据index取embedding，相当于取了两次index，所以当使用了非hist类VarLenSparseFeat时，就会报错。（但由于例子run_din.py中的VarLenSparseFeat均为hist类特征，所以该bug一直未被发现。）
