### ISSUE TITLE
运行run_classification_criteo.py时报错

### ISSUE THREAD

**Issue by TresBienDA** [shenweichen/DeepCTR-Torch#190]
pip install -U deepctr-torch安装好环境
Requirement already satisfied: tensorflow in d:\devtools\anaconda3\envs\pytorch\lib\site-packages (1.2.1)
Requirement already satisfied: markdown>=2.6.8 in d:\devtools\anaconda3\envs\pytorch\lib\site-packages (from tensorflow) (3.3.4)
Requirement already satisfied: html5lib==0.9999999 in d:\devtools\anaconda3\envs\pytorch\lib\site-packages (from tensorflow) (0.9999999)
Requirement already satisfied: protobuf>=3.2.0 in d:\devtools\anaconda3\envs\pytorch\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: backports.weakref==1.0rc1 in d:\devtools\anaconda3\envs\pytorch\lib\site-packages (from tensorflow) (1.0rc1)
Requirement already satisfied: wheel>=0.26 in d:\devtools\anaconda3\envs\pytorch\lib\site-packages (from tensorflow) (0.36.2)
Requirement already satisfied: six>=1.10.0 in d:\devtools\anaconda3\envs\pytorch\lib\site-packages (from tensorflow) (1.15.0)
Requirement already satisfied: numpy>=1.11.0 in d:\devtools\anaconda3\envs\pytorch\lib\site-packages (from tensorflow) (1.19.2)
Requirement already satisfied: bleach==1.5.0 in d:\devtools\anaconda3\envs\pytorch\lib\site-packages (from tensorflow) (1.5.0)
Requirement already satisfied: werkzeug>=0.11.10 in d:\devtools\anaconda3\envs\pytorch\lib\site-packages (from tensorflow) (1.0.1)
Requirement already satisfied: importlib-metadata in d:\devtools\anaconda3\envs\pytorch\lib\site-packages (from markdown>=2.6.8->tensorflow) (4.0.1)
Requirement already satisfied: zipp>=0.5 in d:\devtools\anaconda3\envs\pytorch\lib\site-packages (from importlib-metadata->markdown>=2.6.8->tensorflow) (3.4.1)
Requirement already satisfied: typing-extensions>=3.6.4 in d:\devtools\anaconda3\envs\pytorch\lib\site-packages (from importlib-metadata->markdown>=2.6.8->tensorflow) (3.10.0.0)

然后运行run_classification_criteo.py时报错
Traceback (most recent call last):
  File "E:/pyproject/DeepCTR-Torch/examples/run_classification_criteo.py", line 8, in <module>
    from deepctr_torch.inputs import SparseFeat, DenseFeat, get_feature_names
  File "E:\pyproject\DeepCTR-Torch\deepctr_torch\__init__.py", line 2, in <module>
    from . import models
  File "E:\pyproject\DeepCTR-Torch\deepctr_torch\models\__init__.py", line 1, in <module>
    from .wdl import WDL
  File "E:\pyproject\DeepCTR-Torch\deepctr_torch\models\wdl.py", line 11, in <module>
    from .basemodel import BaseModel
  File "E:\pyproject\DeepCTR-Torch\deepctr_torch\models\basemodel.py", line 24, in <module>
    from tensorflow.python.keras._impl.keras.callbacks import CallbackList
ModuleNotFoundError: No module named 'tensorflow.python.keras'

环境
 - python 3.6
 - torch 1.6.0
 - deepctr-torch 0.2.7
 
请问这个如何解决？感激

**Comment by zanshuxun** [comment]
tensorflow版本换成1.4及以上的试试
