### ISSUE TITLE
训练 DIN 的时候, loss 一直是负的

### ISSUE THREAD

**Issue by Echo0117** [shenweichen/DeepCTR-Torch#191]
**Describe the question(问题描述)**
你好，请问一下我训练 DIN 的时候, loss 一直是负的，validation acc 也一直没变化。。（我的样本数量大概是有一万多个用户，十万多条历史数据）。另外我的数值数据也都归一化了，麻烦问一下还有可能是什么原因造成的呀

**Additional context**
![image](https://user-images.githubusercontent.com/54064209/122569851-bd477b80-d07d-11eb-8702-f938921ed835.png)

**Operating environment(运行环境):**
 - python version：3.7
 - torch version：1.8.1+cu102 
 - deepctr-torch version：0.2.7

**Comment by zanshuxun** [comment]
用的是什么loss？把数据换成criteo_sample.txt试试看有没有这个问题
