### ISSUE TITLE
neg sampling algorithm

### ISSUE THREAD

**Issue by Data-Designer** [shenweichen/DeepCTR-Torch#205]
https://github.com/shenweichen/DeepCTR-Torch/blob/b4d8181e86c2165722fa9331bc16185832596232/examples/run_dien.py#L40

- Why neg here is the same as pos mentioned before？I dig out the source code but I can't find any negative sampling algorithm. 
- So , neg sampling algorithm need to be defined by ourselves?

**Comment by zanshuxun** [comment]
1. `DeepCTR-Torch/examples/run_dien.py` is just a example to show how to run the model, the input data is sample data.
2. Yes, if you need to use negative sampling in hist features. 1) DeepCTR-Torch concentrates on models. 2) Besides, the data format of different users is various. Hence, the data preprocessing need to be done by the users according to their dataset.
