### ISSUE TITLE
basemodel.py 中的 201行  model = self.train()  引起的问题

### ISSUE THREAD

**Issue by jzsbioinfo** [shenweichen/DeepCTR-Torch#209]
**Describe the bug(问题描述)**
同样的环境，相同的训练集，训练相同epoch次数，在加入验证集和不加入验证集前后训练结果不同。
 
不加入验证集训练：
`history = model.fit(train_model_input, train_target, batch_size=batch_size, epochs=5,verbose=1 )`

加入验证集训练：
`history = model.fit(train_model_input, train_target, batch_size=batch_size, epochs=5,verbose=1, validation_data= [test_model_input, test_target])`

是否是 basemodel.py 中的 201行  model = self.train()  引起的问题？
或者276行 eval_result = self.evaluate(val_x, val_y, batch_size)  self 修改为 model。

**Comment by zanshuxun** [comment]
验证集的使用会影响训练集产生的数据及效果

## 原因

pytorch中底层有一个base_seed，各种随机操作会改变这个seed。因此val_loader的使用会影响train_loader产生的数据，train的效果也会发送变化。

## 解法

为dataloader指定generator

```python
generator = torch.Generator()
generator.manual_seed(2022)
train_loader = DataLoader(dataset=train_dataset, shuffle=True, batch_size=1, generator=generator)
# Don't pass in the same generator to `valid_loader` if you don't want the RNG to share states and influence one another.
```


详见 https://github.com/pytorch/pytorch/issues/80119
