### ISSUE TITLE
Runtime hints: Please check the latest version manually...

### ISSUE THREAD

**Issue by Master-PLC** [shenweichen/DeepCTR-Torch#210]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR-PyTorch/issues) before you ask the question.

**Describe the question(问题描述)**
When I run "from deepctr_torch.models import *", it prompts "Please check the latest version manually on https://pypi.org/project/deepctr-torch/#history"

**Additional context**

**Operating environment(运行环境):**
 - python version [3.7.10]
 - torch version [1.8]
 - deepctr-torch version [0.2.7]

**Comment by zanshuxun** [comment]
这个是检查版本更新的提示，不影响使用的

**Comment by zanshuxun** [comment]
你运行的环境是不是上不了网？所以会出现这个提示

**Comment by Master-PLC** [comment]
我现在暂时没有使用deepctr了，感谢您的回复
