### ISSUE TITLE
关于多值类别特征的输入

### ISSUE THREAD

**Issue by treeAndRiver** [shenweichen/DeepCTR-Torch#223]
**Describe the question(问题描述)**
请问怎么利用这个库处理多值类别特征呢？
貌似库里面只分了DenseFeat和SparseFeat。

**Comment by zanshuxun** [comment]
看一下examples里的run_din.py

**Comment by treeAndRiver** [comment]
感谢回复！原来就是ValLenSparseFeat。能额外请教您一个问题吗：我做实验发现对于DCN-v2等神经网络类型的模型来说，多值类别特征做成ValLenSparseFeat（也就是一个Field对应一个embedding），效果还比不上直接把多值类别特征分开，分成单个的形式，然后直接当作单值类别特征来处理。是不是如果多值类别特征的维度特别大的情况下，才使用ValLenSparseFeat比较好呢？

**Comment by zanshuxun** [comment]
长度不固定的多值类别特征，咋分成单个的形式？

**Comment by treeAndRiver** [comment]
是这样的，在我的项目中，长度不固定的多值类别特征最多也就几维，所以可以padding缺失补齐，然后分成单个的形式。无论如何，感谢您的回复！

**Comment by ugirc** [comment]
请问下多值类别特征，长度不一致的时候用0来补充，那0对应的embedding会参与注意力机制过程吗，还是会mask掉？

**Comment by treeAndRiver** [comment]
@ugirc 我觉得0对应的embedding也是正常有值的，embedding层里面应该会先做独热编码，不会所谓的mask掉。（你也可以在代码里面把embedding打印出来看看）再者，类别特征往往需要先做映射，完全可以将需要padding的数据映射成第n+1类，而不是用0来代替。

**Comment by ugirc** [comment]
> @ugirc 我觉得0对应的embedding也是正常有值的，embedding层里面应该会先做独热编码，不会所谓的mask掉。（你也可以在代码里面把embedding打印出来看看）再者，类别特征往往需要先做映射，完全可以将需要padding的数据映射成第n+1类，而不是用0来代替。

我仔细看了deepctr中DIN模型的代码逻辑，0对应的embedding确实是有值的，为了在weighted sum pooling中不加入这一部分，在代码里使用了mask和paddding。

当然我看[nn.Embedding()](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html)好像有一个参数padding_idx，是可以直接让这个idx对应的embedding全为0的，只不过deepctr没有这样用而已。
