### ISSUE TITLE
Why is there a linear model in models like DCN which does not have a linear model?

### ISSUE THREAD

**Issue by kwmaeng91** [shenweichen/DeepCTR-Torch#224]
First, thank you for your wonderful open-source codebase. I am really enjoying it.
I have one question. Why do models like DCN or AFN have a linear model? From the paper it seems like they do not have a linear model as in Wide & Deep. For example, I think in DCN the cross model serves as the linear model of Wide & Deep, so it only has cross + deep, not wide (linear).

Am I misunderstanding? Thank you for your help!

**Comment by jiangyzy** [comment]
I have the same questions too.
