### ISSUE TITLE
Running ValueError: y_true contains only one label (1.0)

### ISSUE THREAD

**Issue by xin970909** [shenweichen/DeepCTR-Torch#227]
ValueError: y_true contains only one label (1.0). Please provide the true labels explicitly through the labels argument.
When running DeepFM.py with the dataset criteo_sample.txt provided in "examples" with training batch size=4

**Comment by zanshuxun** [comment]
your `batch_size ` is too small and log_loss cannot be calculated

**Comment by ZhangYuef** [comment]
It seems in your train data there is only **one** label (i.e., 1.0) and lacks other labels (e.g., 0.0). Please check the train/test data split.
