### ISSUE TITLE
What is X in forward function of DeepFM?

### ISSUE THREAD

**Issue by Jeriousman** [shenweichen/DeepCTR-Torch#234]
**Describe the question(问题描述)**

The DeepFM model has forward function which takes X as an input (It is not only for DeepFM but also other models). But What does X look like? As it is an input for forward function, I wanted to check the shape of X and what it is but DeepCTR takes keras fit, predict so the codes dont really show what you put as the input for DeepFM model. Can you tell me the input and pseudo-generate the input data? And where can I check X if Im missing how to check it?

**Comment by zanshuxun** [comment]
This is DeepCTR-Torch repository, and there is no keras fit/predict here. Do you mean [DeepCTR ](https://github.com/shenweichen/DeepCTR)repository?

**Comment by Jeriousman** [comment]
No it is clearly DeepCTR-Torch. 
If you go to ```class BaseModel in models/basemodel.py```,  you can find 
``` 
 def fit(self, x=None, y=None, batch_size=None, epochs=1, verbose=1, initial_epoch=0, validation_split=0.,
            validation_data=None, shuffle=True, callbacks=None):
```
and
```
 def predict(self, x, batch_size=256):
```
But these are 'small x' not 'large X'. If you see ``` class Linear(nn.Module) ``` in /models/basemodel.py,  you can see large X 
``` def forward(self, X, sparse_feat_refine_weight=None): ```. And I believe this is the same input as X in ``` def forward(self, X):```
in models/deepfm.py.
![화면 캡처 2022-03-05 142933](https://user-images.githubusercontent.com/38139484/156887731-5261f7ca-7337-4ff9-aaf6-d3db25991da4.png)


Can you please specify what the X is? the shape and what it is in an example in pseudo generated data with torch at least?

**Comment by zanshuxun** [comment]
It's not keras fit. It's DeepCTR-Torch fit, which is designed in https://github.com/shenweichen/DeepCTR-Torch/blob/master/deepctr_torch/models/basemodel.py#L136

The input `X` could be found here:
https://github.com/shenweichen/DeepCTR-Torch/blob/master/deepctr_torch/models/basemodel.py#L244 , which is derived from train input.

**Comment by Jeriousman** [comment]
I will look it up and tell you about it! Thank you.
