### ISSUE TITLE
AttributeError: 'Embedding' object has no attribute 'shape'

### ISSUE THREAD

**Issue by HenryBao91** [shenweichen/DeepCTR-Torch#243]
**Describe the question(问题描述)**
`AttributeError: 'Embedding' object has no attribute 'shape'`.

**Additional context**
`https://github.com/shenweichen/DeepCTR-Torch/blob/master/deepctr_torch/layers/sequence.py`.  代码 57 行和 67 行，
uiseq_embed_list 变量的类型为 torch.nn.modules.sparse.Embedding ，uiseq_embed_list 没有 shape 方法，
uiseq_embed_list.shape[1] 和 uiseq_embed_list.shape[-1] 报错

**Operating environment(运行环境):**
 - python version [3.8.13]
 - torch version [e.g. 1.11.0]

**Comment by zanshuxun** [comment]
你是运行哪个文件报错的？请给出复现步骤

**To Reproduce(复现步骤)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
