### ISSUE TITLE
import deepctr_torch error

### ISSUE THREAD

**Issue by CFZhai** [shenweichen/DeepCTR-Torch#269]
When I try to import deepctr_torch, the local kernel will die and automatically restart.  
![WX20230118-145751@2x](https://user-images.githubusercontent.com/119619206/213293359-7604f24f-9faf-44f0-8722-f6865d28e39a.png)
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/119619206/213293770-83aff235-c952-4f98-885c-52134350ad59.png">

My local PC is Macbook air M2 2022. memory 16G

But When I switch to the online server (google colab), it is imported successfully.

**Comment by zanshuxun** [comment]
> When I try to import deepctr_torch, the local kernel will die and automatically restart.

Try this again in a terminal instead of the jupyter notebook, then check the result.

**Comment by CFZhai** [comment]
If I try it in a terminal, it also returns error 
<img width="569" alt="image" src="https://user-images.githubusercontent.com/119619206/215155389-6226ab76-b7b4-4c70-9064-711e194ab7a6.png">

**Comment by CFZhai** [comment]
I just figure out the problem is due to the Tensorflow compilation. When I follow the instruction of [https://www.youtube.com/watch?v=5DgWvU0p2bk](https://www.youtube.com/watch?v=5DgWvU0p2bk )
and reinstall the deepctr_torch. I successfully import all packages. 
But I encounter  a new problem , which is I can't update my deepctr_torch to the latest version. ('0.2.9'), Now it is '0.2.2' after using pip install -U deepctr-torch
