### ISSUE TITLE
运行How to add a long dense feature vector as a input to the model?报错

### ISSUE THREAD

**Issue by JunnYu** [shenweichen/DeepCTR-Torch#53]
**Describe the bug(问题描述)**

**To Reproduce(复现步骤)**
https://deepctr-torch.readthedocs.io/en/latest/FAQ.html#how-to-add-a-long-dense-feature-vector-as-a-input-to-the-model 网站中提供的代码运行错误。
basemodel.py中的
np.hstack(list(map(lambda x: np.expand_dims(x, axis=1), x))))
报错
ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Operating environment(运行环境):**
 - python version 3.7
 - torch version 1.2.0
 - deepctr-torch version 0.1.1

**Additional context**

**Comment by shenweichen** [comment]
sorry for this error,please update your code through `pip install -U deepctr-torch` and re-run the code.
