### ISSUE TITLE
Provide learning rate parameter interface

### ISSUE THREAD

**Issue by AmazingDD** [shenweichen/DeepCTR-Torch#56]
I found that there is no interface for users to adjust learning rate for specific algorithm, so can u provide a parameter **lr** when state a algorithm class so that we could change this parameter value

**Comment by shenweichen** [comment]
@AmazingDD  hi, please read the doc about how to use and  optimizer instance with defined learning rate
https://deepctr-torch.readthedocs.io/en/latest/deepctr_torch.models.basemodel.html#deepctr_torch.models.basemodel.BaseModel.compile
