### ISSUE TITLE
suggetion for a new function

### ISSUE THREAD

**Issue by jiangxiaoshuaiya** [shenweichen/DeepCTR-Torch#58]
I think is there any possible to add a function such as early_stop_rounds, like xgb.

**Comment by zanshuxun** [comment]
we add this feature in new version(v0.2.3), please use `pip install -U deepctr-torch` to upgrade. [example](https://deepctr-torch.readthedocs.io/en/latest/FAQ.html#set-learning-rate-and-use-earlystopping)：

```python
from deepctr_torch.callbacks import EarlyStopping, ModelCheckpoint

es = EarlyStopping(monitor='val_auc', min_delta=0, verbose=1, patience=0, mode='max', baseline=None)
mdckpt = ModelCheckpoint(filepath='model.ckpt', monitor='val_auc', mode='max', verbose=1, save_best_only=True)
model.fit(train_model_input,train[target].values,batch_size=256,epochs=10,verbose=2,validation_split=0.2,callbacks=[es,mdckpt])
```
api in detail：https://tensorflow.google.cn/api_docs/python/tf/keras/callbacks/EarlyStopping
