### ISSUE TITLE
请问还是不是不支持 变长序列跟sparse features共享emb？

### ISSUE THREAD

**Issue by markeloff** [shenweichen/DeepCTR-Torch#59]
Please refer to the [FAQ](https://deepctr-doc.readthedocs.io/en/latest/FAQ.html) in doc and search for the [related issues](https://github.com/shenweichen/DeepCTR-PyTorch/issues) before you ask the question.

**Describe the question(问题描述)**
A clear and concise description of what the question is.

**Additional context**

**Operating environment(运行环境):**
 - python version [e.g. 3.6]
 - torch version [e.g. 1.2.0,]
 - deepctr-torch version [e.g. 0.1.0,]

**Comment by ZhangYuef** [comment]
目前`v0.2.0`版本已经加入变长序列的支持了。
