### ISSUE TITLE
如果我不做CTR用他来做一个药品推荐系统的话，最后是一个softmax来看TOP5的概率这样做可以吗

### ISSUE THREAD

**Issue by JasinlikeEatingOrange** [shenweichen/DeepCTR-Torch#60]
就是用户输入一些症状描述，我加一些环节让他变成我们输入的Onehot的样子，然后做预测，这样可以做吗？然后是一个很多类的输出概率，我只取前五就行了~

**Comment by fengmaozheng** [comment]
我也需要一个类似的模型，ctr预测应该一次性算出所有商品的可能性才好取 top k来推荐或者重新排序。

**Comment by DaiJitao** [comment]
请问问题解决了吗？

**Comment by zanshuxun** [comment]
可以使用二分类模型对候选的每个item（这里即药品）都进行预测，按照预测分数排序取top5即可。需要的话可以通过召回来缩小候选集。
