### ISSUE TITLE
Dense value is not for DNN input in AutoInt

### ISSUE THREAD

**Issue by SongRb** [shenweichen/DeepCTR-Torch#62]
**Describe the bug(问题描述)**
In original paper of AutoInt, dense value is also converted to a fix length embedding. Using a DNN for dense value list may be wrong.

https://github.com/shenweichen/DeepCTR-Torch/blob/687a094135fa597697d926782a5634c79b627dac/deepctr_torch/models/autoint.py#L98

**Comment by shenweichen** [comment]
hi, in the previous version of deepctr(not deepctr-torch) we converted the dense value to embedding vectors.Now in order to be compatible with apis of other modes, we changed the implementation of dense values in autoint.

**Comment by diff7** [comment]
You should rename it because it is very confusing when looking at the paper and your code.

**Comment by abedshantti** [comment]
@shenweichen do you know where I can find the transformation of dense values into embedding vectors? I have been trying to locate it in the AutoInt code file but it is not there. Or am I supposed to define all the features as sparse before defining the model (as in the criteo classification example script)?
