### ISSUE TITLE
InteractingLayer的softmax dim = 1 是不是错了感觉应该等于3

### ISSUE THREAD

**Issue by InkdyeHuang** [shenweichen/DeepCTR-Torch#63]
**Describe the bug(问题描述)**

**To Reproduce(复现步骤)**

**Operating environment(运行环境):**
 - python version [e.g. 3.5, 3.6]
 - torch version [e.g. 1.1.0, 1.2.0]
 - deepctr-torch version [e.g. 0.1.0,]

**Additional context**

**Comment by Matafight** [comment]
+1

**Comment by shenweichen** [comment]
感谢！会在下个版本修复！

**Comment by ZhangYuef** [comment]
> **Describe the bug(问题描述)**
> A clear and concise description of what the bug is.
> 
> **To Reproduce(复现步骤)**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Operating environment(运行环境):**
> 
> * python version [e.g. 3.5, 3.6]
> * torch version [e.g. 1.1.0, 1.2.0]
> * deepctr-torch version [e.g. 0.1.0,]
> 
> **Additional context**
> Add any other context about the problem here.

已经在最新版本中修复啦，详见 [link](https://github.com/shenweichen/DeepCTR-Torch/blob/bb6064343e8d271843bbd7efb9e8f3ecbd5d42b3/deepctr_torch/layers/interaction.py#L390)
