### ISSUE TITLE
Why the fm only work for sparse feature columns？

### ISSUE THREAD

**Issue by jianzheng-china** [shenweichen/DeepCTR-Torch#65]
![image](https://user-images.githubusercontent.com/43208634/69424256-1a286600-0d63-11ea-96bf-b10310f4d374.png)

**Comment by jianzheng-china** [comment]
Supplement：this part of code in the file called deepfm.py

**Comment by tianpunchh** [comment]
because fm is a vector product, dense feature can be thought of only 1 element vector, it cannot product with other embedding feature vectors.
