### ISSUE TITLE
为什么运行会无端卡住

### ISSUE THREAD

**Issue by linzihan-backforward** [shenweichen/DeepCTR-Torch#66]
**Describe the bug(问题描述)**
运行example中的crite_classification时，在训练完一个epoch后就卡住了，无故不往下运行，不知道什么原因，其他的example也一样，第一个epoch的tqdm显示完就卡住了

**Operating environment(运行环境):**
 - python 3.6 
 - pytorch 1.3.1

**Comment by zanshuxun** [comment]
我这边没能复现 请问用最新版的代码还有这个问题吗？
