### ISSUE TITLE
CCPM model中ConvLayer(nn.Module) Layer层没有加tanh的激活层

### ISSUE THREAD

**Issue by jimzhu** [shenweichen/DeepCTR-Torch#67]
原论文2.3节指出在pooling layer后加入tanh激活。

**Comment by zanshuxun** [comment]
考虑到您提出此issue时的时间较早，我找到了当时的代码：
https://github.com/shenweichen/DeepCTR-Torch/blob/687a094135fa597697d926782a5634c79b627dac/deepctr_torch/layers/interaction.py#L607-L612
tanh激活层是有的，但顺序是在pooling之前。
不知代码作者@Zengai 当时是否是考虑到很多CNN模型的顺序都是卷积-激活-池化？

但按照CCPM论文中的描述，tanh应该是在pooling之后：

> We apply a non-linear function for outputs of pooling layers.

**Comment by zanshuxun** [comment]
啊……仔细想了一下，这里的max pooling跟tanh的先后顺序好像是无所谓的
