### ISSUE TITLE
multi gpus

### ISSUE THREAD

**Issue by GUANFULUO** [shenweichen/DeepCTR-Torch#73]
How to run the demo with multiple GPUs？

**Comment by zanshuxun** [comment]
multiple gpus running is supported in [v0.2.6](https://github.com/shenweichen/DeepCTR-Torch/releases/tag/v0.2.6) , please use `pip install -U deepctr-torch` to upgrade. 

example: https://deepctr-torch.readthedocs.io/en/latest/FAQ.html#how-to-run-the-demo-with-multiple-gpus
