### ISSUE TITLE
Planning to add DIN and DIEN in Torch?

### ISSUE THREAD

**Issue by Curlykonda** [shenweichen/DeepCTR-Torch#77]
**Describe the question(问题描述)**
Are you planning to add a PyTorch implementation of DIN and DIEN? If so, what's the current time horizon? Or how could one go about helping with that? 

**Additional context**
Since there already exists a DIEN implementation in Tensorflow, this could be used as a great reference point for converting the model to PyTorch.

**Comment by ZhangYuef** [comment]
Hi 

> **Describe the question(问题描述)**
> Are you planning to add a PyTorch implementation of DIN and DIEN? If so, what's the current time horizon? Or how could one go about helping with that?
> 
> **Additional context**
> Since there already exists a DIEN implementation in Tensorflow, this could be used as a great reference point for converting the model to PyTorch.

Hi @Curlykonda ,  there is a DIN in DeepCTR-PyTorch but it hasn't passed all the tests. You could help to test it on the `dev` branch!
