### ISSUE TITLE
Pytest for AFM model is not stable

### ISSUE THREAD

**Issue by ZhangYuef** [shenweichen/DeepCTR-Torch#82]
# Describe the bug(问题描述)
If we run several `pytest`, some of them would result in  failure of `tests/models/AFM_test.py `

# To Reproduce(复现步骤) 
1. Go to main directory: `DeepCTR-Torch/`
2. Run `pytest` in command line for multiple times
3. See error

# Operating environment(运行环境):
 - python version: `3.6.4`
 - torch version: `1.3.1`
 - deepctr-torch version: `dev` branch

# Additional context
![image](https://user-images.githubusercontent.com/20250982/76590967-1ce2ce80-64ac-11ea-953c-1df5ba4bf8ed.png)

**Details of the error**:
![image](https://user-images.githubusercontent.com/20250982/76590990-2ff59e80-64ac-11ea-90ab-0f8322e68a74.png)

**Comment by shenweichen** [comment]
we have solved this issue in new version , please use `pip install -U deepctr-torch` to upgrade.
