### ISSUE TITLE
alpha should be wrappered with Parameter in Dice

### ISSUE THREAD

**Issue by hzlawliet** [shenweichen/DeepCTR-Torch#93]
As model.parameters() used in optim, alpha in Dice should use nn.parameter.Parameter to wrapper. Just like alpha in pRelu. Otherwise this paramter will fix to init value in the training process.

**Comment by ZhangYuef** [comment]
> As model.parameters() used in optim, alpha in Dice should use nn.parameter.Parameter to wrapper. Just like alpha in pRelu. Otherwise this paramter will fix to init value in the training process.

Thanks for pointing out! I realize it should be `nn.parameter.Parameter` for `alpha` since `alpha` is learnable. 

Open this issue for future bug fix. Thanks again for this help!

**Comment by zanshuxun** [comment]
Hi, we have solved this issue in [v0.2.4](https://github.com/shenweichen/DeepCTR-Torch/releases/tag/v0.2.4), please use `pip install -U deepctr-torch` to upgrade.
