### ISSUE TITLE
if mengshen can share the data all in a link?,  this data now is too small ,thanks!!

### ISSUE THREAD

**Issue by liheyong** [shenweichen/DeepCTR-Torch#94]
if mengshen can share the data all in a link?,  this data now is too small ,thanks!!

**Comment by zanshuxun** [comment]
datasets:
criteo: https://www.kaggle.com/c/criteo-display-ad-challenge/data
movielens: https://grouplens.org/datasets/movielens/
avazu: https://www.kaggle.com/c/avazu-ctr-prediction/data
