### ISSUE TITLE
deepctr_torch(version 0.2.1) din can't support pytorch at version 1.5.0 above

### ISSUE THREAD

**Issue by Lanxueyun** [shenweichen/DeepCTR-Torch#98]
**Describe the bug(问题描述)**
if run the din example code with pytorch 1.5.0 , get error as bellow 
**RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation**

**To solve(解决)**
1. reinstall pytorch to 1.4.0 

**Operating environment(运行环境):**
 - python version [e.g. 3.7]
 - torch version [e.g. 1.5.0]
 - deepctr-torch version [e.g. 0.2.0,]

**Additional context**

**Comment by ZhangYuef** [comment]
> **Describe the bug(问题描述)**
> if run the din example code with pytorch 1.5.0 , get error as bellow
> **RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation**
> 
> **To solve(解决)**
> 
> 1. reinstall pytorch to 1.4.0
> 
> **Operating environment(运行环境):**
> 
> * python version [e.g. 3.7]
> * torch version [e.g. 1.5.0]
> * deepctr-torch version [e.g. 0.2.0,]
> 
> **Additional context**
> Add any other context about the problem here.

Thanks for reporting!

**Comment by shenweichen** [comment]
we have solved this issue in new version , please use `pip install -U deepctr-torch` to upgrade.
